VIA_ENABLE = yes
VIAL_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
GRAVE_ESC_ENABLE = yes
MAGIC_ENABLE = yes
BOOTMAGIC_ENABLE = yes

COMMAND_ENABLE = no
CONSOLE_ENABLE = no

QMK_SETTINGS = yes
# LTO_ENABLE = yes