VIA_ENABLE = yes
VIAL_ENABLE = yes
OLED_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
WPM_ENABLE = no
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
GRAVE_ESC_ENABLE = yes
MAGIC_ENABLE = yes
BOOTMAGIC_ENABLE = yes

COMMAND_ENABLE = no
CONSOLE_ENABLE = no

QMK_SETTINGS = yes
LTO_ENABLE = yes

KEY_OVERRIDE_ENABLE = no

NKRO_ENABLE = yes

SPLIT_KEYBOARD = yes

DYNAMIC_MACRO_ENABLE = yes


LED_INDICATORS_ENABLE = yes